version: '3'
services:
  mongo:
    image: mongo:4.4.4
    container_name: mongoNestJS
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=api
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data-4.4:/data/db
